# vim:ft=kitty
background_opacity 0.8

# Neovim
scrollback_pager nvim --cmd "set eventignore=FileType" +"nnoremap q ZQ" +"call nvim_open_term(0, {})" +"set nomodified nolist" +"$" -
map ctrl+shift+h show_scrollback
map ctrl+shift+n launch --type=overlay nvim +terminal +startinsert

# Theming
include ~/.local/state/quickshell/user/generated/terminal/kitty-theme.conf

# Font
font_family      JetBrains Mono Nerd Font
font_size 20.0
symbol_map U+e000-U+e00a,U+e0a0-U+e0a2,U+e0a3,U+e0b0-U+e0b3,U+e0b4-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ea60-U+ec1e,U+ed00-U+efce,U+f000-U+f2ff,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono
symbol_map U+2022,U+2192,U+2500,U+256F,U+2570,U+E0B0-U+E0D4,U+EA71,U+F00D,U+F04B,U+F12C,U+F409,U+F40F,U+F456,U+F46D,U+F4A5,U+F4A9,U+F4B6,U+F024B,U+F02A4,U+F0388,U+F062C,U+F0725,U+F0AA2,U+1FB00-U+1FBFF JetBrains Mono Nerd Font

# Cursor
cursor_shape beam
cursor_trail 1
cursor_trail_decay 0.1 0.42
cursor_trail_start_threshold 0

# Padding (why weird value? consistency with foot)
window_margin_width 21.75

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell fish

# Copy
map ctrl+c    copy_or_interrupt

# Search
map ctrl+f   launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
map kitty_mod+f   launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

# Scroll & Zoom
scrollbar scrolled-and-hovered
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size current +1
map ctrl+equal  change_font_size current +1
map ctrl+kp_add  change_font_size current +1
map ctrl+minus       change_font_size current -1
map ctrl+underscore       change_font_size current -1
map ctrl+kp_subtract       change_font_size current -1
map ctrl+0 change_font_size current 0
map ctrl+kp_0 change_font_size current 0
