# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Let the children of some windows float while they themselves tile
windowrulev2 = float, class:^(steam)$
windowrulev2 = tile, class:^(steam)$,title:^(Steam)$
windowrulev2 = float, class:^(QQ)$
windowrulev2 = tile, class:^(QQ)$,title:^(QQ)$
windowrulev2 = float, class:^(wechat)$
windowrulev2 = tile, class:^(wechat)$,title:^(微信)$

# Discard the blank window of Wine
windowrulev2 = workspace special:garbage silent, class:^$, title:^$, xwayland:1
windowrulev2 = noinitialfocus, class:^$, title:^$, xwayland:1
windowrulev2 = noborder, class:^$, title:^$, xwayland:1

# Firefox
windowrulev2 = float, class:^(firefox)$, title:^(我的足迹)$
windowrulev2 = center, class:^(firefox)$, title:^(我的足迹)$
windowrulev2 = size 800 600, class:^(firefox)$, title:^(我的足迹)$

