#!/usr/bin/env bash

# Get the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# The parent directory of scripts/ is the root of the repo
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

# Exit on error
set -e

# --- Kitty Configuration Injection ---
KITTY_CONF="$HOME/.config/kitty/kitty.conf"
KITTY_EXTRA="$REPO_ROOT/files/extra/kitty/kitty.conf"
KITTY_MARKER="# --- Hyprland Init Config ---"

if [[ -f "$KITTY_EXTRA" ]]; then
    echo "Injecting Kitty configuration..."
    mkdir -p "$(dirname "$KITTY_CONF")"
    
    # Create kitty.conf if it doesn't exist
    if [[ ! -f "$KITTY_CONF" ]]; then
        touch "$KITTY_CONF"
    fi

    # Check for marker to ensure idempotency
    if grep -qF "$KITTY_MARKER" "$KITTY_CONF"; then
        echo "Kitty configuration already injected. Skipping."
    else
        echo "" >> "$KITTY_CONF"
        echo "$KITTY_MARKER" >> "$KITTY_CONF"
        cat "$KITTY_EXTRA" >> "$KITTY_CONF"
        echo "Kitty configuration updated."
    fi
else
    echo "Warning: Kitty extra configuration not found at $KITTY_EXTRA"
fi

# --- Fish Configuration Injection ---
# Using conf.d is cleaner and safer than modifying config.fish directly
FISH_CONF_D="$HOME/.config/fish/conf.d"
FISH_INIT_FILE="$FISH_CONF_D/hyprland-init.fish"
FISH_EXTRA="$REPO_ROOT/files/extra/fish/config.fish"

if [[ -f "$FISH_EXTRA" ]]; then
    echo "Injecting Fish configuration..."
    mkdir -p "$FISH_CONF_D"
    
    # We simply copy the file to conf.d, which is idempotent by default (overwrites)
    # We wrap the variables in an interactive check if not already present in the source
    
    echo "# Generated by hyprland-init script" > "$FISH_INIT_FILE"
    echo "if status is-interactive" >> "$FISH_INIT_FILE"
    
    # Extract content, excluding the source line if we want to handle it differently,
    # but for conf.d, we can just put everything in.
    # However, the original logic separated vars and source. 
    # Let's just dump the content but ensure it's safe.
    
    # Read extra config and append to our conf.d file
    # We indent it for the 'if status is-interactive' block
    while IFS= read -r line; do
        echo "    $line" >> "$FISH_INIT_FILE"
    done < "$FISH_EXTRA"
    
    echo "end" >> "$FISH_INIT_FILE"
    
    echo "Fish configuration installed to $FISH_INIT_FILE"
else
    echo "Warning: Fish extra configuration not found at $FISH_EXTRA"
fi

cp -v "$REPO_ROOT/files/hyprland/"* ~/.config/hypr/custom/
